"""add base entities

Revision ID: 05083b56d106
Revises: 8027b98a61b2
Create Date: 2024-11-06 16:09:08.913298

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '05083b56d106'
down_revision = '8027b98a61b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_login'), 'user', ['login'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_login'), table_name='user')
    # ### end Alembic commands ###
