"""add columns

Revision ID: 8027b98a61b2
Revises: 6329b98ac97c
Create Date: 2024-11-06 11:42:18.433743

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8027b98a61b2'
down_revision = '6329b98ac97c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('stack_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('interview', sa.Column('event_datetime', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'interview', 'stacktag', ['stack_tag'], ['tag_code'])
    op.add_column('interviewslot', sa.Column('from_datetime', sa.DateTime(), nullable=False))
    op.add_column('interviewslot', sa.Column('to_datetime', sa.DateTime(), nullable=False))
    op.drop_column('interviewslot', 'event_datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviewslot', sa.Column('event_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('interviewslot', 'to_datetime')
    op.drop_column('interviewslot', 'from_datetime')
    op.drop_constraint(None, 'interview', type_='foreignkey')
    op.drop_column('interview', 'event_datetime')
    op.drop_column('interview', 'stack_tag')
    # ### end Alembic commands ###
