"""add base entities

Revision ID: f957427b36cc
Revises: 39c4f2b1489d
Create Date: 2024-11-07 20:25:58.385400

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f957427b36cc'
down_revision = 'c8952cd53594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviewslot', sa.Column('duration', sa.Float(), nullable=False))
    op.add_column('interviewslot', sa.Column('technology', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False))
    op.drop_column('interviewslot', 'to_datetime')
    op.drop_column('interviewslot', 'max_applicant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviewslot', sa.Column('max_applicant', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('interviewslot', sa.Column('to_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('interviewslot', 'technology')
    op.drop_column('interviewslot', 'duration')
    # ### end Alembic commands ###
